---
whitelist:
- MIT
- Apache 2.0
- BSD
- ruby
- BSD 2-Clause
ignore_groups:
- test
- development
ignore_dependencies:
#- bundler
dependencies_file_dir: './doc/licenses'
project_name: password_changer
